Solved #701: Added improved logged out message
tursodatabase/turso-cli pull request #703
Opened 2023-10-24 12:40 UTC by PruthviThakor

- changed logged out message to **You are not logged in, please login with `turso auth login` before running other commands.** as mentioned in issues #701 .

2023-10-24 12:52 UTC, haaawk reviewed
This will still prefix the message with "Error:" no?

2023-10-24 12:53 UTC, haaawk approved these changes

2023-10-24 13:10 UTC, haaawk commented
> > This will still prefix the message with "Error:" no?
> 
> So It should be like normal message instead of error?

That's my understanding.

2023-10-24 13:11 UTC, haaawk commented on internal/cmd/db.go
> +		return "", fmt.Printf("You are not logged in, please login with %s before running other commands.", internal.Emph("turso auth login"))
Does this even compile? Why are you returning string as an error?

2023-10-24 13:12 UTC, haaawk requested changes
I think returning string as an error is not the right way to fix the problem

2023-10-24 13:15 UTC, PruthviThakor commented
> I think returning string as an error is not the right way to fix the problem

yeah I get that, We souldn't change Error to Print

2024-01-19 18:46 UTC, notrab commented
I think it's fine to return a string instead of an error here. The original issue https://github.com/tursodatabase/turso-cli/issues/701 was to improve the wording by this kind of behaviour being common. Removing `error: ` prefix does that.

2024-05-05 19:05 UTC, haaawk commented
#701 is properly fixed by https://github.com/tursodatabase/turso-cli/pull/851

2024-05-05 19:05 UTC, closed without merging